version: '3.8'

services:
  hakatonpostgres:
    image: postgres:12.0
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5435"
    ports:
      - "5435:5435"
    command: -p 5435
    restart: always
  hakatonapp:
    build: './'
    image: hakatonapp:latest
    restart: always
    environment:
      DATABASE_URL: 'jdbc:postgresql://hakatonpostgres:5435/postgres'
    ports:
      - 80:8992
    depends_on:
      - hakatonpostgres
